### ISSUE TITLE
node env works on local but problems when serving from IP addresses

### ISSUE THREAD

**Issue by prizm1** [fmacpro/horseman-article-parser-ui#23]
Besides some styling, the ui comes out exactly like the below. {{these}} {{labels}} are shown before a run is made and , nothing happens when you click "analyze". you got the best parser bro, i added a summarizer you'd prob like. I just dont know why can build it local but cant get it running on server.

Page Inspector - Page Analysis Tool
Web Page Inspection Tool. Sentiment Analysis, Keyword Extraction & Named Entity Recognition

Page URL 

e.g. google.com
Use Tor Proxy (Enables analysis of .onion URLs)
Analyse
{{status}}
Google Preview
{{article.title}}
{{article.url}}
{{article.metadescription}}

Sentiment
{{Article.Sentiment.Result}}
Keyphrases
{{Keyphrase.Keyphrase}}
People
{{Person.Normal}}
Organisations & Groups
{{ORG.NORMAL}}
Places
{{Place.Normal}}
Spelling
Line {{Warning.Line}}{{warning.reason}}
{{article.title}}
Description

**Comment by fmacpro** [comment]
Did you manage to get it working @prizm1 ? Sorry for the delay in coming back to you.
